name: Run Playwright tests inside Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tests \
            -w /tests \
            mcr.microsoft.com/playwright:v1.39.0-jammy \
            bash -c "npm ci && npx playwright test"

      - name: Upload Playwright report (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
